import * as PIXI from 'pixi.js';
import { TILE_SIZE, MapManager } from './MapManager';
import { GameStateManager } from './GameStateManager';

export interface GridCoord {
    x: number;
    y: number;
}

export class PathManager {
    public pathCells: GridCoord[] = [];
    public startNodePos: PIXI.Point = new PIXI.Point(0, 0);
    public endNodePos: PIXI.Point = new PIXI.Point(0, 0);

    public macroPath: GridCoord[] = [];
    public pathVectors: { dx: number, dy: number }[] = [];
    public microCols: number = 0;
    private playableTop: number = 1;

    constructor() {
        // Path will be generated by WaveManager during prepareWave
    }

    public generatePath(waveNumber: number) {
        let success = false;
        let attempts = 0;
        while (!success && attempts < 100) {
            success = this.attemptMacroGeneration(waveNumber);
            attempts++;
        }
        
        // CACHE VECTORS FOR ENEMIES (based on macro centers for fluidity)
        const pts = this.getPathPoints();
        this.pathVectors = [];
        for (let i = 0; i < pts.length - 1; i++) {
            const dx = pts[i+1].x - pts[i].x;
            const dy = pts[i+1].y - pts[i].y;
            const dist = Math.sqrt(dx*dx + dy*dy);
            if (dist > 0) {
                this.pathVectors.push({ dx: dx/dist, dy: dy/dist });
            } else {
                this.pathVectors.push({ dx: 1, dy: 0 });
            }
        }
    }

    private attemptMacroGeneration(waveNumber: number): boolean {
        const currentTileSize = MapManager.calculateTileSize();
        const visibleCols = Math.floor(window.innerWidth / currentTileSize / 2) * 2;
        const dashboardPadding = Math.max(110, Math.min(150, window.innerHeight * 0.2));
        const visibleRows = Math.floor((window.innerHeight - dashboardPadding) / currentTileSize);
        this.microCols = visibleCols;

        this.playableTop = 1;
        const playableBottom = visibleRows - 2; // EXTRA BUFFER
        const playableRows = playableBottom - this.playableTop + 1;

        if (playableRows < 4) return false;

        // TUTORIAL OVERRIDE: CENTERED STRAIGHT PATH
        if (waveNumber === 0) {
            const macroRows = Math.floor(playableRows / 2);
            const midMacroY = Math.floor(macroRows / 2);
            this.macroPath = [];
            const macroCols = Math.floor(visibleCols / 2);
            
            for (let mx = 0; mx < macroCols; mx++) {
                this.macroPath.push({ x: mx, y: midMacroY });
            }
            
            this.buildMicroPathFromMacro(this.macroPath);
            return true;
        }

        // REAL GAME GENERATION
        const macroCols = Math.ceil(this.microCols / 2);
        const macroRows = Math.floor(playableRows / 2);

        if (macroCols < 4 || macroRows < 2) return false;

        const startY = Math.floor(Math.random() * macroRows);
        let path: GridCoord[] = [];
        let visited = new Set<string>();
        
        const state = GameStateManager.getInstance();
        const wealthMult = state.credits > 2500 ? 0.75 : 1.0; 
        const complexityFactor = 0.4 + (Math.random() * 0.25); 
        const targetLength = Math.floor(macroCols * macroRows * complexityFactor * wealthMult);

        const dfs = (mx: number, my: number): boolean => {
            if (mx === macroCols - 1) {
                if (path.length >= Math.min(macroCols, targetLength / 2)) {
                    path.push({ x: mx, y: my });
                    return true;
                }
                return false;
            }

            visited.add(`${mx},${my}`);
            path.push({ x: mx, y: my });

            const dirs = [
                { dx: 1, dy: 0, weight: 15 },   
                { dx: 0, dy: 1, weight: 10 },  
                { dx: 0, dy: -1, weight: 10 }, 
                { dx: -1, dy: 0, weight: 1 }   
            ];

            dirs.sort((a, b) => (Math.random() * b.weight) - (Math.random() * a.weight));

            for (const d of dirs) {
                const nx = mx + d.dx;
                const ny = my + d.dy;
                
                if (nx >= 0 && nx < macroCols && ny >= 0 && ny < macroRows) {
                    if (nx === 0 && mx !== 0) continue; 
                    if (!visited.has(`${nx},${ny}`)) {
                        // STRICT ISOLATION: Check neighbors to prevent "thick" paths
                        let neighborCount = 0;
                        const checkDirs = [{dx:1, dy:0}, {dx:-1, dy:0}, {dx:0, dy:1}, {dx:0, dy:-1}];
                        for (const cd of checkDirs) {
                            if (visited.has(`${nx + cd.dx},${ny + cd.dy}`)) neighborCount++;
                        }
                        
                        if (neighborCount === 1) { // Only the current node should be a neighbor
                            if (dfs(nx, ny)) return true;
                        }
                    }
                }
            }

            path.pop();
            visited.delete(`${mx},${my}`);
            return false;
        };

        if (dfs(0, startY)) {
            this.macroPath = path;
            this.buildMicroPathFromMacro(path);
            return true;
        }
        return false;
    }

    private buildMicroPathFromMacro(macroPath: GridCoord[]) {
        this.pathCells = [];
        for (let i = 0; i < macroPath.length; i++) {
            const mc = macroPath[i];
            const microX = mc.x * 2;
            const microY = this.playableTop + mc.y * 2;

            // PUSH ONLY THE ANCHOR - MapManager handles 2x2 stamp
            this.pathCells.push({ x: microX, y: microY });

            if (i === 0) {
                this.startNodePos = new PIXI.Point(0, (microY + 1) * TILE_SIZE);
            }
            if (i === macroPath.length - 1) {
                // Ensure it reaches the absolute right edge
                this.endNodePos = new PIXI.Point(window.innerWidth, (microY + 1) * TILE_SIZE);
                
                // Add padding cells to ensure the black path rects reach the edge
                let lastX = microX;
                while (lastX < this.microCols) {
                    lastX += 2;
                    this.pathCells.push({ x: lastX, y: microY });
                }
            }
        }
    }

    public getPathPoints(): PIXI.Point[] {
        const pts: PIXI.Point[] = [];
        if (this.macroPath.length === 0) return pts;

        // True start at edge
        const firstY = this.playableTop + this.macroPath[0].y * 2;
        pts.push(new PIXI.Point(0, (firstY + 1) * TILE_SIZE));

        // Macro centers
        for (const mc of this.macroPath) {
            const microX = mc.x * 2;
            const microY = this.playableTop + mc.y * 2;
            pts.push(new PIXI.Point((microX + 1) * TILE_SIZE, (microY + 1) * TILE_SIZE));
        }

        // True end at edge
        const last = this.macroPath[this.macroPath.length - 1];
        const lastY = this.playableTop + last.y * 2;
        pts.push(new PIXI.Point(window.innerWidth, (lastY + 1) * TILE_SIZE));

        return pts;
    }
}
